### ISSUE TITLE
combat monster size bug

### ISSUE THREAD

**Issue by drademacher** [dhaunac/fictional-spoon#29]
== error message

Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at combat.Combat.tick(Combat.java:233)
    at framework.StateControl.tick(StateControl.java:47)
    at framework.Window$1.handle(Window.java:89)
    at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$484(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(Unknown Source)
    at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(Unknown Source)
    at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(Unknown Source)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

== source code

// let monster attack
if (blocked < 0) {
    blocked = delayTicks - 1;

```
Random rnd = new Random();
int rndMonsterIndex;
if (monster.size() == 1) {
    rndMonsterIndex = 0;
} else {
    rndMonsterIndex = rnd.nextInt(monster.size() - 1);
}
Monster attackMonster = monster.get(rndMonsterIndex);

attackMonster.doAttack(player);
```

} else {
    blocked--;
}

== description

Assumption about the error:
There are no more monster and then it tries to find a random one. Then the input argument rnd.nextInt(...) gets negative.

**Comment by jensharder91** [comment]
This should not happen, because the lines:

```
        if (monster.size() == 0) {
            // opponent dead
            if (opponent != null) {
                opponent.setDead(true);
            }
            this.stop();
        }
```

can you reproduce the error @dhaunac
